FROM --platform=linux/amd64 gradle:8.5.0-jdk21-alpine

ARG SERVER_PORT
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG SECRET_TOKEN
ARG EMAIL_SENDER
ARG EMAIL_PASSWORD

ENV SERVER_PORT=$SERVER_PORT
ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV SECRET_TOKEN=$SECRET_TOKEN
ENV EMAIL_SENDER=$EMAIL_SENDER
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD

WORKDIR todolist-api

COPY . .

RUN ./gradlew build

ENTRYPOINT ["./gradlew","bootRun"]
